fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fix_it:
    resource: "@FixItBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
